name: Deploy Flask App to GitHub Pages

on:
  push:
    branches:
      - main  # ここはデプロイしたいブランチに変更してください

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Build static files
        run: |
          python -c "
          import os
          import shutil
          output_dir = 'static_output'
          if os.path.exists(output_dir):
            shutil.rmtree(output_dir)
          shutil.copytree('templates', output_dir)
          "


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static_output
