name: Flask to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Flaskとその他の依存関係をインストール
      - name: Install dependencies
        run: |
          pip install flask
          pip install gunicorn

      # Flaskサーバーをバックグラウンドで実行し、HTMLを生成
      - name: Generate static HTML files
        run: |
          mkdir -p public
          nohup gunicorn --bind 127.0.0.1:5000 app:app &
          sleep 5  # サーバーが起動するまでの待機
          curl http://127.0.0.1:5000 > public/index.html  # ルートパスのHTMLを保存
          # 必要なら他のルートのHTMLも保存可能
          # 例: curl http://127.0.0.1:5000/about > public/about.html

      # 静的ファイル (CSS, JS など) を public ディレクトリにコピー
      - name: Copy static files
        run: |
          cp -R static/ public/static/

      # GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # 静的HTMLと静的ファイルが含まれたディレクトリ
