name: ワークフローの名前

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Install Flask
              run: pip3 install flask
            - name: Run Flask
              run: python app.py
